FROM klaemo/couchdb:2.0

COPY local.ini /opt/couchdb/etc/local.d/

#RUN /opt/couchdb/bin/couchdb & (sleep 3 && curl -X PUT http://emad:emad@127.0.0.1:5984/_users)
# RUN /opt/couchdb/bin/couchdb & (sleep 3 && curl -X PUT http://127.0.0.1:5984/_replicator)
# RUN /opt/couchdb/bin/couchdb & (sleep 3 && curl -X PUT http://127.0.0.1:5984/_global_changes)
# RUN curl -X PUT http://127.0.0.1:5984/_replicator
# RUN curl -X PUT http://127.0.0.1:5984/_global_changes
